#! /bin/sh

sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        6
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  \#E9AD79
bspc config normal_border_color	  \#79B5e9
bspc config active_border_color	  \#FFB1CE
bspc config presel_feedback_color \#91D1AF
bspc config click_to_focus		  none

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
