#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton&
killall -q polybar
sh /home/rlkandela/.config/polybar/scripts/spotify/launchlistener.sh&
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.50
bspc config border_width        6
bspc config window_gap          20
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color    \#E9AD79
bspc config normal_border_color     \#79B5e9
bspc config active_border_color     \#FFB1CE
bspc config presel_feedback_color   \#91D1AF

bspc config click_to_focus          none

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Opera desktop='^2' follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a TelegramDesktop desktop='^4' follow=on
